// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squader.Infrastructure.DAL;

namespace Squader.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180618203738_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("Squader.DomainModel.Announcements.Announcement", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("AuthorId");

                    b.Property<DateTime>("ChangedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ShortDescription");

                    b.Property<Guid>("TeamId");

                    b.Property<string>("Title");

                    b.Property<string>("requirementsJson")
                        .HasColumnName("Requirements");

                    b.Property<string>("tagsJson")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Squader.DomainModel.Teams.Team", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("ChangedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Squader.DomainModel.Teams.UserTeam", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("ChangedAt");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("Deleted");

                    b.Property<int>("TeamRoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("Squader.DomainModel.Users.User", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("ChangedAt");

                    b.Property<string>("City");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Forename");

                    b.Property<string>("HashPassword");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Role");

                    b.Property<string>("Salt");

                    b.Property<string>("Surname");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
